import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";

type OfferPageProps = { eyebrow: string; title: React.ReactNode; intro: string; offer: string; deliverables: string[]; fit: string; timeline: string };

export function OfferPage({ eyebrow, title, intro, offer, deliverables, fit, timeline }: OfferPageProps) {
  return <><SiteNav /><main className="pt-14"><section className="fl-container offer-hero py-20"><div className="max-w-4xl"><span className="eyebrow">{eyebrow}</span><h1 className="mt-5 max-w-4xl text-balance font-semibold tracking-tight">{title}</h1><p className="mt-6 max-w-2xl text-[18px] leading-relaxed text-[var(--on-surface-variant)]">{intro}</p><Link href="/contact" className="mono cta-button mt-8 inline-block" style={{ background: "var(--primary-container)" }}>Start with a review</Link></div></section><section className="fl-container offer-detail pb-20"><div className="offer-statement"><span className="mono text-[12px] uppercase tracking-[0.08em] text-[var(--primary-container)]">The offer</span><h2 className="mt-4 max-w-3xl text-[30px] font-semibold leading-tight md:text-[40px]">{offer}</h2></div><div className="offer-columns mt-12"><div><h3 className="text-[20px] font-semibold">What you get</h3><ul className="mt-5 grid gap-0 border-t border-[var(--outline-variant)]">{deliverables.map((item) => <li key={item} className="border-b border-[var(--outline-variant)] py-4 text-[15px] text-[var(--on-surface-variant)]"><span className="mr-3 text-[var(--primary-container)]">+</span>{item}</li>)}</ul></div><div className="offer-aside"><div><span className="eyebrow">Built for</span><p className="mt-2 text-[15px] leading-relaxed text-[var(--on-surface-variant)]">{fit}</p></div><div><span className="eyebrow">Working window</span><p className="mt-2 text-[15px] leading-relaxed text-[var(--on-surface-variant)]">{timeline}</p></div><Link href="/contact" className="mono secondary-link mt-3">Talk through your situation <span aria-hidden>→</span></Link></div></div></section></main><SiteFooter /></>;
}
