// lib/questions.js
//
// This defines the RULE-BASED branching layer: deterministic, free, instant.
// Each section has a list of questions. Some questions only appear
// if a condition on prior answers is met (see `showIf`).
//
// The AI-DRIVEN layer (dynamic follow-up questions generated by Claude)
// is handled separately in app/api/next-question/route.js and is used
// on top of this — typically once per section, after the base questions
// in that section are answered.

export const SECTIONS = [
  {
    id: 'overview',
    title: 'About Your Business',
    questions: [
      { id: 'orgName', type: 'text', label: 'Business Name', required: true },
      {
        id: 'orgType',
        type: 'radio',
        label: 'Which best describes your business?',
        required: true,
        options: [
          { value: 'product', label: 'Product-based (e.g. retail, e-commerce)' },
          { value: 'service', label: 'Service-based (e.g. agency, consulting, trades)' },
          { value: 'membership', label: 'Membership / Subscription-based' },
          { value: 'other', label: 'Mixed / Other' },
        ],
      },
      {
        id: 'orgSize',
        type: 'radio',
        label: 'Roughly how many customers/clients do you serve?',
        required: true,
        options: [
          { value: 'small', label: 'Under 100' },
          { value: 'medium', label: '100–500' },
          { value: 'large', label: '500+' },
        ],
      },
    ],
  },
  {
    id: 'operations',
    title: 'Current Operations',
    questions: [
      {
        id: 'challenges',
        type: 'checkbox',
        label: 'What are your biggest operational challenges? (select all that apply)',
        required: true,
        options: [
          'Scheduling & bookings',
          'Registration & onboarding',
          'Billing & payments',
          'Customer retention & engagement',
          'Performance/data tracking',
          'Admin tasks eating staff time',
          'Customer communication',
        ],
      },
      {
        id: 'meetSchedulingDetail',
        type: 'textarea',
        label: 'How do you currently handle inventory and fulfillment logistics?',
        // Only shown for product-based orgs — rule-based branching example
        showIf: (answers) => answers.orgType === 'product' || answers.orgType === 'other',
      },
      {
        id: 'classCapacityDetail',
        type: 'textarea',
        label: 'How do you manage scheduling capacity and availability?',
        // Only shown for service-based orgs
        showIf: (answers) => answers.orgType === 'service' || answers.orgType === 'other',
      },
      {
        id: 'schedulingSystem',
        type: 'select',
        label: 'How do you currently manage scheduling & registrations?',
        required: true,
        options: [
          'Paper/manual system',
          'Spreadsheets',
          'Dedicated software',
          'Custom-built system',
          'Multiple systems',
          'Not systematized',
        ],
      },
    ],
  },
  {
    id: 'technology',
    title: 'Technology & Capacity',
    questions: [
      {
        id: 'techComfort',
        type: 'radio',
        label: "How comfortable is your team with new technology?",
        required: true,
        options: [
          { value: 'very', label: 'Very comfortable — early adopters' },
          { value: 'moderate', label: 'Moderately comfortable — open to learning' },
          { value: 'limited', label: 'Limited comfort' },
          { value: 'low', label: 'Low comfort — needs significant support' },
        ],
      },
      {
        id: 'systems',
        type: 'checkbox',
        label: 'What systems do you currently use?',
        options: ['Accounting software', 'CRM or customer database', 'Email marketing tool', 'Website platform'],
      },
    ],
  },
  {
    id: 'priorities',
    title: 'Business Priorities',
    questions: [
      {
        id: 'painPoint',
        type: 'textarea',
        label: "What's your biggest pain point right now?",
        required: true,
      },
      {
        id: 'aiExperience',
        type: 'radio',
        label: 'Have you considered AI or automation before?',
        options: [
          { value: 'never', label: 'Never considered it' },
          { value: 'explored', label: "Explored it, haven't acted" },
          { value: 'implemented', label: 'Implemented something already' },
        ],
      },
    ],
  },
  {
    id: 'budget',
    title: 'Budget & Decision Making',
    questions: [
      {
        id: 'budget',
        type: 'radio',
        label: 'Is there budget allocated for improvements this year?',
        required: true,
        options: [
          { value: 'yes', label: 'Yes, we have budget' },
          { value: 'maybe', label: 'Maybe, pending discussion' },
          { value: 'consider', label: 'No budget now, but would consider it' },
          { value: 'no', label: 'No' },
        ],
      },
      { id: 'email', type: 'email', label: 'Email address', required: true },
      { id: 'phone', type: 'tel', label: 'Phone number', required: false },
    ],
  },
];

// Returns only the questions that should currently be visible for a section,
// given the answers collected so far.
export function visibleQuestions(sectionId, answers) {
  const section = SECTIONS.find((s) => s.id === sectionId);
  if (!section) return [];
  return section.questions.filter((q) => (q.showIf ? q.showIf(answers) : true));
}
